### ISSUE TITLE
TerrainType not matching map.generateRoom

### ISSUE THREAD

**Issue by ghost** [jkingry/screeps-mod-mapgen#5]
Any specific reason why not follow map.generateRoom's random terrain/swampType?

http://support.screeps.com/hc/en-us/community/posts/209435465-PS-Changelog-build-27

https://github.com/screeps/backend-local/blob/master/lib/cli/map.js#L447

**Comment by jkingry** [comment]
Well you can give a number like in 'generateRoom' or leave it undefined and it has sand begaviour. But I added a third option where you can also give a function to generate a (random) number. 

I did this because it's what I do for the border rooms. I only use terrain types 1 to 3
